### PR TITLE
Add axol.io faucet to README.md

### PR DESCRIPTION
**Pull request by Hydepwns**
happy to help support testnet!

### CODE REVIEW

**Comment by barnabasbusa** [comment]
Looks like the faucet's tunnel is broken.

Screenshot 2024-06-18 at 14 48 00

**Comment by Hydepwns** [comment]
Screenshot 2024-07-02 at 12 23 16 AM
should be working now, had to reconfigure.

**Comment by Hydepwns** [comment]
cc @barnabasbusa could you take a peek

**Comment by barnabasbusa** [comment]
LGTM cc: @pk910

**Review by barnabasbusa — APPROVED** [review]

**Comment by barnabasbusa** [comment]
Seems to be working.

**Pull request merged**
