### PR TITLE
Add zhongfu 10k keys

### PR DESCRIPTION
**Pull request by zhongfu**

### CODE REVIEW

**Comment by q9f** [comment]
The genesis state is full (see #24) - thank you for your contribution.

You can still run validators by making normal deposits after genesis. Reply to this comment if you didn't receive an allocation after genesis and I can take care of that.

**Comment by zhongfu** [comment]
> The genesis state is full (see #24) - thank you for your contribution.
> 
> You can still run validators by making normal deposits after genesis. Reply to this comment if you didn't receive an allocation after genesis and I can take care of that.

@q9f now that things have quietened down -- would it be a good time for me to ask about this?

**Comment by q9f** [comment]
Yes, what's your address?

**Comment by zhongfu** [comment]
`0x8989859156070A1Bc64f8833DbbC19dC1Bd1A2b8`/`zhongfu.eth`, thanks!

**Comment by q9f** [comment]
Sent!

**Pull request closed without merging**
